# Generated by Django 2.0.7 on 2023-01-10 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sending_user',
            new_name='username',
        ),
    ]
